spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpringBoot-javatechie/ecom-common-configuration
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9595